### ISSUE TITLE
Layout on Failed Jobs broken after search.

### ISSUE THREAD

**Issue by Plofstoffel** [suadev/chrome-hangfire-search-extension#2]
Hi,
When using the filter on the Failed Jobs page of the dashboard the layout of the jobs are not correct. Please see the screenshot.
![HangfireDashboard](https://user-images.githubusercontent.com/21218423/112278280-f3de4780-8c82-11eb-91b1-36d9039fb0ea.png)

Thank you for a great plugin!

**Comment by Plofstoffel** [comment]
I have created a pull request to fix the issue. But it can be done better by someone with more jQuery experience.

#3

**Comment by suadev** [comment]
@Plofstoffel Thank you, but, what is the issue exactly? I can't see it because you blurred on it.

**Comment by Plofstoffel** [comment]
The layout is not correct and you cannot click on the More details link as the row containing the detail is not there.
